{
  "tagList": [
    "jupyterhub",
    "jupyter-remote-desktop-proxy",
    "Exposure of Resource to Wrong Sphere",
    "CRITICAL"
  ],
  "title": "Jupyter Remote Desktop Proxy vulnerability",
  "description": "Jupyter Remote Desktop Proxy allows you to run a Linux Desktop on a JupyterHub. jupyter-remote-desktop-proxy was meant to rely on UNIX sockets readable only by the current user since version 3.0.0, but when used with TigerVNC, the VNC server started by jupyter-remote-desktop-proxy were still accessible via the network. This vulnerability does not affect users having TurboVNC as the vncserver executable. This issue is fixed in 3.0.1.",
  "score": 9,
  "cvssVersion": "4.0",
  "vector": "CVSS:4.0/AV:A/AC:L/AT:P/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H",
  "id": "CVE-2025-32428",
  "url": "https://github.com/jupyterhub/jupyter-remote-desktop-proxy/security/advisories/GHSA-vrq4-9hc3-cgp7",
  "isNewlyPublishedCVE": true,
  "raw": {
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
      "cveId": "CVE-2025-32428",
      "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
      "state": "PUBLISHED",
      "assignerShortName": "GitHub_M",
      "dateReserved": "2025-04-08T10:54:58.367Z",
      "datePublished": "2025-04-14T23:29:40.494Z",
      "dateUpdated": "2025-04-14T23:29:40.494Z"
    },
    "containers": {
      "cna": {
        "title": "Jupyter Remote Desktop Proxy makes TigerVNC accessible via the network and not just via a UNIX socket as intended",
        "problemTypes": [
          {
            "descriptions": [
              {
                "cweId": "CWE-668",
                "lang": "en",
                "description": "CWE-668: Exposure of Resource to Wrong Sphere",
                "type": "CWE"
              }
            ]
          }
        ],
        "metrics": [
          {
            "cvssV4_0": {
              "attackVector": "ADJACENT",
              "attackComplexity": "LOW",
              "attackRequirements": "PRESENT",
              "privilegesRequired": "NONE",
              "userInteraction": "NONE",
              "vulnConfidentialityImpact": "HIGH",
              "vulnIntegrityImpact": "HIGH",
              "vulnAvailabilityImpact": "HIGH",
              "subConfidentialityImpact": "HIGH",
              "subIntegrityImpact": "HIGH",
              "subAvailabilityImpact": "HIGH",
              "baseScore": 9,
              "baseSeverity": "CRITICAL",
              "vectorString": "CVSS:4.0/AV:A/AC:L/AT:P/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H",
              "version": "4.0"
            }
          }
        ],
        "references": [
          {
            "name": "https://github.com/jupyterhub/jupyter-remote-desktop-proxy/security/advisories/GHSA-vrq4-9hc3-cgp7",
            "tags": [
              "x_refsource_CONFIRM"
            ],
            "url": "https://github.com/jupyterhub/jupyter-remote-desktop-proxy/security/advisories/GHSA-vrq4-9hc3-cgp7"
          },
          {
            "name": "https://github.com/jupyterhub/jupyter-remote-desktop-proxy/commit/7dd54c25a4253badd8ea68895437e5a66a59090d",
            "tags": [
              "x_refsource_MISC"
            ],
            "url": "https://github.com/jupyterhub/jupyter-remote-desktop-proxy/commit/7dd54c25a4253badd8ea68895437e5a66a59090d"
          }
        ],
        "affected": [
          {
            "vendor": "jupyterhub",
            "product": "jupyter-remote-desktop-proxy",
            "versions": [
              {
                "version": ">= 3.0.0, < 3.0.1",
                "status": "affected"
              }
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
          "shortName": "GitHub_M",
          "dateUpdated": "2025-04-14T23:29:40.494Z"
        },
        "descriptions": [
          {
            "lang": "en",
            "value": "Jupyter Remote Desktop Proxy allows you to run a Linux Desktop on a JupyterHub. jupyter-remote-desktop-proxy was meant to rely on UNIX sockets readable only by the current user since version 3.0.0, but when used with TigerVNC, the VNC server started by jupyter-remote-desktop-proxy were still accessible via the network. This vulnerability does not affect users having TurboVNC as the vncserver executable. This issue is fixed in 3.0.1."
          }
        ],
        "source": {
          "advisory": "GHSA-vrq4-9hc3-cgp7",
          "discovery": "UNKNOWN"
        }
      }
    }
  }
}